campaigns/urls.py
from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^create/$', views.CampaignCreateView.as_view(), name='create'),
    url(r'^delete/(?P<slug>[\w-]+)/$', views.CampaignDeleteView.as_view(), name='delete'),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.CampaignUpdateView.as_view(), name='update'),
    url(r'^list/$', views.CampaignUserListView.as_view(), name='list'),
    url(r'^check/$', views.CheckUrl.as_view(), name='check'),
    url(r'^(?P<slug>[\w-]+)/$', views.CampaignDetailView.as_view(), name='detail'),
]

config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
from django.contrib.staticfiles.views import serve as serve_static
from django.views.decorators.cache import never_cache

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap

from pushthought import views
from programs.sitemaps import ProgramSitemap

from actions.views import SubmitCongressEmail, MyActivityView
from users.views import ProfileView

from .sitemaps import StaticViewSitemap
from .views import LoggedInView, oauth_callback, oauth_login, SaveUserByEmailView, login


sitemaps = {
    'static': StaticViewSitemap,
    'programs': ProgramSitemap
}

urlpatterns = [
    # Admin
    url(r'^admin/', include(admin.site.urls)),

    url(r'^test/(?P<twitter_screen_name>.*)', views.get_user_by_twitter_screen_name, name='test'),
    url(r'^$', views.HomeView.as_view(), name='home',),
    url(r'^home/$', views.HomeView.as_view(), name='home',),
    url(r'^browse/$', views.browse_view, name='browse'),
    url(r'^browse_campaigns/$', views.browse_campaigns_view, name='browse_campaigns'),
    url(r'^contact_immediately/$', views.ContactImmediatelyView.as_view(), name='contact_immediately'),
    url(r'^campaign_landing/$', views.CampaignLandingView.as_view(), name='campaign_landing'),
    url(r'^email_signup/$', SaveUserByEmailView.as_view(), name='email_signup'),
    url(r'^profile/', ProfileView.as_view(), name='profile'),
    # url(r'^content_landing/(?P<program_id>\w+)/$', views.ContentLandingView.as_view(), name='content_landing'),

    url(r'^accounts/twitter/login/callback/$', oauth_callback, name='twitter_callback'),
    url(r'^accounts/twitter/login/$', oauth_login, name='twitter_login'),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/my-activity/$', MyActivityView.as_view(),
        name='my_activity'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^program/', include('programs.urls', namespace='programs')),
    url(r'^congress/', include('congress.urls', namespace='congress')),
    url(r'^c/', include('campaigns.urls', namespace='campaign')),

    url(r'^is_logged_in/$', LoggedInView.as_view(), name='user_logged_in'),


    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # congress email
    url(r'^submit_congress_email/$', SubmitCongressEmail.as_view()),
    url(r'^submit_congress_captcha', views.submit_congress_captcha_view, name='submit_congress_captcha_view'),
    url(r'^submit-email/(?P<email>.*)', views.submit_email, name='submit_email'),
    url(r'^send-contact/', views.send_contact, name='send_contact'),

    url(r'^content_landing/$', views.content_landing_empty, name='content_landing_empty'),
    # url(r'^content_landing/(?P<program_id>\w+)', views.content_landing, name='content_landing'),
    url(r'^get_congress_email_fields', views.get_congress_email_fields_view, name='get_congress_email_fields_view'),
    url(r'^get_congress_with_zip/(?P<zip>\w+)', views.get_congress_with_zip_view, name='get_congress_with_zip'),
    url(r'^get_congress_with_location', views.get_congress_with_location_view, name='get_congress_with_location'),
    # url(r'^get_congress_with_location/(?P<lat>\w+)/(?P<long>\w+)', views.get_congress_with_location_view, name='get_congress_with_location'),
    url(r'^leaving', views.leaving, name='leaving'),
    url(r'^program_detail/(?P<programId>\w+)', views.program_detail, name='program_detail'),
    # url(r'^api', views.api,name='api',),
    # Twitter Verification
    url(r'^verify_twitter', views.verify_twitter),
    # url(r'^verify_twitter/(?P<programId>\w+)/(?P<segmentId>\w+)/(?P<tweet>.*)',
    #     views.verify_twitter),
    url(r'^verify_catch', views.SendTweetView.as_view(),name='verify_catch'),
    # url(r'^store_email_fields_in_session', views.StoreEmailFieldsInSessionView.as_view(),name='store_email_fields_in_session'),


    # Backburner
    url(r'^snippets', include('snippets.urls')),
    url(r'^prime', include('prime.urls')),
    # url(r'^account/(?P<user_pk>\d+)/(?P<program_pk>\d+)/addsegment', views.add_segment, name='add_segment'),
    # url(r'^account/(?P<user_pk>\d+)/(?P<program_pk>\d+)/(?P<segment_pk>\d+)', views.segment_menu, name='segment_menu'),
    # url(r'^account/(?P<user_pk>\d+)/(?P<program_pk>\d+)', views.segment_list, name='segment_list'),

    #account home
    url(r'^account/(?P<user_pk>\w+)', views.account_home, name='account_home'),

    # Action Menu
    url(r'^action_menu/(?P<programId>\w+)/(?P<segmentId>\w+)/fed_representative',views.fed_rep_action_menu),
    url(r'^action_menu/(?P<programId>\w+)/(?P<segmentId>\w+)/petition',views.petition),
    url(r'^action_menu/(?P<programId>\w+)/(?P<segmentId>\w+)/communication',views.petition),
    url(r'^action_menu/(?P<programId>\w+)/(?P<segmentId>\w+)',views.action_menu),
    url(r'^user_signin_form',views.user_signin_form, name='user_signin_form'),
    url(r'^login_form',views.login_form, name='login_form'),
    url(r'^logout', views.user_logout, name='user_logout'),



    # segment JPGM9mmcKV   program JPGM9mmcKV
    # url(r'^action_menu/(?P<segment_pk>\d+)/(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})', views.action_menu,
    # url(r'^action_menu/(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})-(<segment_name>)', views.action_menu, name='action_menu'),

    url(r'^about',views.about, name='about'),
    # url(r'^register', views.register, name='register'),
    # url(r'^login', views.user_login, name='login'),
    url(r'^contact',views.contact,name='contact'),
    #url(r'^pushthought/', views.), # ADD THIS NEW TUPLE!
    #url(r'^programs/', include('pushthought.urls')),
    # url(r'^accounts/', include('registration.backends.default.urls')),
    #potentially comment out line above
]

urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += url(r'^static/(?P<path>.*)$', never_cache(serve_static)),

prime/urls.py
from django.conf.urls import url
from prime import views

urlpatterns = [
    url(r'^prime/$', views.segmentapi_list),
    url(r'^prime/(?P<pk>[0-9]+)/$', views.segmentapi_detail),
]

campaigns/models.py
from __future__ import unicode_literals

from django_extensions.db.models import TimeStampedModel

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from utils.models import CounterMixin


class Campaign(CounterMixin, TimeStampedModel):
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)
    tweet_text = models.TextField(blank=True, null=True)
    email_text = models.TextField(blank=True, null=True)
    link = models.URLField(blank=True, null=True, max_length=10000)
    user = models.ForeignKey(User, blank=True, null=True)
    active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('campaign:detail', args=[str(self.slug)])

    def __str__(self):
        return self.slug

    @property
    def email_count(self):
        return self.actions.filter(email__isnull=False).count()

    @property
    def tweet_count(self):
        return self.actions.filter(tweet__isnull=False).count()

    @property
    def action_count(self):
        return self.actions.count()

campaigns/forms.py
from django import forms

from twitter_text.validation import Validation as TweetValidation

from . import models


class CampaignEditingBaseForm(forms.ModelForm):
    TWEET_MAX_LENGTH = 280
    # Max username length is 15, plus "@" before and a space after.
    TWEET_MENTION_PLACEHOLDER_LENGTH = 17

    def clean_tweet_text(self):
        value = self.cleaned_data['tweet_text']
        if TweetValidation(value).tweet_length() + \
                self.TWEET_MENTION_PLACEHOLDER_LENGTH > self.TWEET_MAX_LENGTH:
            raise forms.ValidationError("Too long.")
        return value


class CampaignForm(CampaignEditingBaseForm):
    class Meta:
        model = models.Campaign
        fields = ('slug', 'title', 'description', 'image', 'tweet_text', 'email_text', 'link', )
        widgets = {
            'link': forms.widgets.TextInput(),
        }

    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        for name in self.fields:
            self.fields[name].widget.attrs['class'] = '{0} {1}'.format('field-input', 'field-input-'+name)
        self.fields['slug'].error_messages['unique'] = \
            'That url is already taken.'

    def clean(self):
        cleaned_data = super(CampaignForm, self).clean()
        tweet = cleaned_data.get("tweet_text")
        email = cleaned_data.get("email_text")
        if not tweet and not email:
            # Only do something if both fields are empty.
            raise forms.ValidationError(
                "Please fill out suggested text for email, tweet, or both."
            )

class CampaignUpdateForm(CampaignEditingBaseForm):
    class Meta:
        model = models.Campaign
        fields = ('title', 'description', 'image', 'tweet_text', 'email_text', 'link',)
        widgets = {
            'link': forms.widgets.TextInput(),
        }

    def __init__(self, *args, **kwargs):
        super(CampaignUpdateForm, self).__init__(*args, **kwargs)
        for name in self.fields:
            self.fields[name].widget.attrs['class'] = '{0} {1}'.format('field-input', 'field-input-'+name)

    def clean(self):
        cleaned_data = super(CampaignUpdateForm, self).clean()
        tweet = cleaned_data.get("tweet_text")
        email = cleaned_data.get("email_text")
        if not tweet and not email:
            # Only do something if both fields are empty.
            raise forms.ValidationError(
                "Please fill out suggested text for email, tweet, or both."
            )

campaigns/views.py
from django.views.generic import DetailView, CreateView, DeleteView, View, ListView, UpdateView
from django.http import JsonResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models, forms


class CampaignDetailView(DetailView):
    model = models.Campaign

    def get_queryset(self):
        queryset = super(CampaignDetailView, self).get_queryset()
        return queryset.filter(active=True)

    def get_context_data(self, **kwargs):
        context = super(CampaignDetailView, self).get_context_data(**kwargs)

        if self.request.session.get('alertList'):
            context['alertList'] = self.request.session['alertList']
            del self.request.session['alertList']
        return context


class CampaignUserListView(LoginRequiredMixin, ListView):
    model = models.Campaign

    def get_queryset(self):
        queryset = super(CampaignUserListView, self).get_queryset()
        return queryset.filter(user=self.request.user).order_by('id')


class CampaignDeleteView(DeleteView):
    model = models.Campaign
    success_url = 'campaign:list'

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(CampaignDeleteView, self).get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj


    def delete(self, request, *args, **kwargs):
        """
        Calls the delete() method on the fetched object and then
        redirects to the success URL.
        """
        self.object = self.get_object()
        success_url = reverse(self.get_success_url())
        self.object.active = not self.object.active
        self.object.save()
        return HttpResponseRedirect(success_url)


class CampaignCreateView(LoginRequiredMixin, CreateView):
    model = models.Campaign
    form_class = forms.CampaignForm

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super(CampaignCreateView, self).form_valid(form)

    def handle_no_permission(self):
        messages.info(self.request,
                      "You must log in to create a campaign.")
        return super(CampaignCreateView, self).handle_no_permission()


class CampaignUpdateView(UpdateView):
    model = models.Campaign
    form_class = forms.CampaignUpdateForm

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(CampaignUpdateView, self).get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj


class CheckUrl(LoginRequiredMixin, View):
    def get(self, request):
        slug = request.GET.get('slug')
        current = request.GET.get('current')
        exists = models.Campaign.objects.filter(slug=slug).exists()
        if slug == current:
            exists = False
        return JsonResponse({'result': exists})

templates/campaigns/campaign_form.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/clean.css' %}">
<link rel="stylesheet" href="{% static 'css/campaign_form.css' %}">

{% endblock %}
{% block title %}{{object.title}}{% endblock %}
{# Push Thought-Browse#}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 ">
      <form  enctype="multipart/form-data" method="post" id="campaign-form">{% csrf_token %}
        <input type="hidden" id="current_slug" value="{{object.slug}}">
        <div class="container-standard container-standard-form">
          {% if form.non_field_errors %}
          <div class="alert alert-danger">
            {% for error in form.non_field_errors %}
            {{error}}
            {% endfor %}
          </div>
          {% endif %}
          <h2 class="form-title">Create custom campaign for messaging congress</h2>
          <p class="field-label field-label-sub-heading">(all fields editable after creation except Push Thought URL)</p>

          <div class="field-group field-group-title">
            <div class="field-label-container">
              <p class="field-label field-label-title">Campaign Title</p>
              <p class="field-label field-label-title-note">This is the first thing people will see about your Messaging Campaign. Get their attention with a short title that focuses on the change you’d like them to support.</p>
            </div>
            {% if form.title.errors %}
            <div class="alert alert-danger">
              {% for error in form.title.errors %}
              {{error}}
              {% endfor %}
            </div>
            {% endif %}
            <div class="field-input-container">
              {{form.title}}
              {# <input name="title" class="field-input field-input-title" value="{% if form.instance.title %}{{ form.instance.title }}{% endif %}" required>#}
            </div>
          </div>
          <div class="field-group">
            <div class="field-label-container">
              <p class="field-label field-label-description">Description</p>
              <p class="field-label field-label-description-note">People are more likely to support your Messaging Campaign if it’s clear why you care. Explain how this change will impact you, your family, or your community. We recommend putting an empty line between paragraphs for readability.</p>
            </div>
            {% if form.description.errors %}
            <div class="alert alert-danger">
              {% for error in form.description.errors %}
              {{error}}
              {% endfor %}
            </div>
            {% endif %}
            <div class="field-input-container">
              {{form.description}}
              {# <textarea name="description" class="field-input field-input-description" required>{% if form.instance.description  %}{{ form.instance.description }}{% endif %} </textarea>#}

            </div>
          </div>
          <div class="field-group">
            <div class="field-label-container">
              <p class="field-label field-label-image">Image (optional)</p>
              <p class="field-label field-label-image-subLabel">71px width x 100px  height or equvalent ratio works best</p>
            </div>
            {% if form.image.errors %}
            <div class="alert alert-danger">
              {% for error in form.image.errors %}
              {{error}}
              {% endfor %}
            </div>
            {% endif %}
            <div class="field-input-container input-file">
              {{form.image}}
              <p class="btn btn-primary btn-input">Browse</p>
              <span id="file-text">No file chosen</span>
              {# <input name="image" accept="image/*" class="field-input field-input-image" type="file" value="{% if form.instance.image %}{{ form.instance.image }}{% endif %}">#}
            </div>
          </div>
          <div class="field-group">
            <div class="field-label-container">
              <p class="field-label field-label-suggestions">must complete at least one: suggested tweet or suggested email</p>
            </div>
            <div class="suggested-message-container">
              <div class="tweet-suggested-message-container">
                <div class="suggested-tweet-container">
                  {% if form.tweet_text.errors %}
                  <div class="alert alert-danger">
                    {% for error in form.tweet_text.errors %}
                    {{error}}
                    {% endfor %}
                  </div>
                  {% endif %}
                   <p class="field-label field-label-tweet-text">1) Suggested tweet text</p>
                   <p class="field-label-tweet-sublabel"><span class="ten-point">(name inserted automatically at beginning)</span></p>
                   <p class="field-label field-label-tweet-note">(max 280 characters, count already includes twitter name)<br></p>
                  <p class="field-label field-label-tweet-intro">@[twitter name will be inserted], </p>
                  {{form.tweet_text}}
                  {# <textarea name="tweet_text" class="field-input field-input-tweet-text" name="field-input-tweet-text">{% if form.instance.tweet_text %}{{ form.instance.tweet_text }}{% endif %}</textarea>#}
                  <p class="tweet-letter-count"></p>
                </div>
                <div class="suggested-email-container">
                  {% if form.email_text.errors %}
                  <div class="alert alert-danger">
                    {% for error in form.email_text.errors %}
                    {{error}}
                    {% endfor %}
                  </div>
                  {% endif %}
                  <p class="field-label field-label-email-text">2) Suggested email text</p>
                  <p class="field-label-email-sublabel" style="margin-bottom:0px;"><span class="ten-point">(tip: borrow text from description)</span></p>
                  <p class="field-label-email-sublabel"><span class="ten-point">(name inserted automatically at beginning)</span></p>
                  <p class="field-label field-label-email-intro">Congressperson [name will be inserted],</p>
                  {{form.email_text}}
                  {# <textarea name="email_text" class="field-input field-input-email-text" name="field-input-email-text" >{% if form.instance.email_text %}{{ form.instance.email_text }}{% endif %}</textarea>#}
                </div>
              </div>
            </div>

            <div class="field-label-container">
              <div>

                <p class="field-label field-label-url">URL on Push Thought</p>
                <p class="field-label field-label-url-subsublabel">(shorter is better for sharing)</p>
                <p class="field-label field-label-url-subsublabel">(cannot be changed once created)</p>
                <p class="field-label field-label-url-sublabel">www.pushthought/c/{{ object.slug }}</p>
                {% if form.slug.errors %}
                <div class="alert alert-danger">
                  {% for error in form.slug.errors %}
                  {{error}}
                  {% endfor %}
                </div>
                {% endif %}
                {{form.slug}}
                {# <input id="slug" name="slug" class="field-input field-input-url" value="{{form.instance.slug}}" {% if object %}readonly{% endif %}>#}
                <div style="margin-top:10px;">
                  <div id="check_result" style="color:green;">Free</div>
                </div>
                {% if form.link.errors %}
                <div class="alert alert-danger">
                  {% for error in form.link.errors %}
                  {{error}}
                  {% endfor %}
                </div>
                {% endif %}
                <p class="field-label field-label-link-to-info">Link to more information</p>
                {{form.link}}
                {# <input name="link" class="field-input field-input-link-to-more-info" value="{% if form.instance.link %}{{ form.instance.link }}{% endif %}">#}
                <p class="field-label field-label-url-subsublabel">(link to your organization or website)</p>

                <div style="margin-top:40px;">
                  <button id="submit" class="btn-lg">{% if object %}SAVE CHANGES{% else %}CREATE CAMPAIGN{% endif %}</button>
                </div>
              </div>
            </div>

          </div>
        </div>
      </form>
    </div>
  </div>
</div>


{% endblock %}

{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script>
        check_url = '{% url 'campaign:check' %}'
    </script>
    <script src="{% static 'js/twitter-text-1.14.7.min.js' %}"></script>
    <script src="{% static 'js/content_landing_success_messages.js' %}"></script>
    <script src="{% static 'js/content_landing.js' %}"></script>
    <script src="{% static 'js/check_campaign.js' %}"></script>
    <script src="{% static 'js/campaign_form.js' %}"></script>
{% csrf_token %}
{% endblock %}

templates/campaigns/campaign_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block css %}

<!--<link rel="stylesheet" href="{% static 'css/campaign-landing.css' %}">-->
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
<link rel="stylesheet" href="{% static 'css/content-landing.css' %}">
<link rel="stylesheet" href="{% static 'css/campaign_list.css' %}">

{% endblock %}
{% block title %}Push Thought-Browse{% endblock %}


{% block content %}
    <div id="content-container" class="row">
    {% if object_list %}

        <div class="list-page-title">My campaigns</div>

        <div>
            <table id="campaign-table" border="0" width="60%" align="center">
                <tr>
                    <th></th>
                    <!--<th width="50%">Title</th>-->
                    <!--<th>Actions</th>-->
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                {% for campaign in object_list %}
                    <tr>
                        <td class="list-campaign-counter">{{ forloop.counter }}</td>
                        <td class="list-campaign-title" align="left">{{ campaign.title }}{% if not campaign.active %} | INACTIVE{% endif %}</td>
                        <td></td>
                        <td><a href="{% url 'campaign:detail' campaign.slug %}"><button>View</button></a></td>
                        <td><a href="{% url 'campaign:update' campaign.slug %}"><button>Edit</button></a></td>
                        <td>
                            <form method="post" action="{% url 'campaign:delete' campaign.slug %}">
                            {% csrf_token %}
                            <button class="button-toggle-active">{% if not campaign.active %}Restore{% else %}X{% endif %}</button>
                            </form>
                        </td>
                    <tr>
                    </tr>
                        <td></td>
                        <td>
                            <div class="email-count">
                                <span class="title">Emails</span>
                                <span class="list-value">{{ campaign.email_count }}</span>
                            </div>
                            <div class="tweet-count">
                                <span class="title">Tweets</span>
                                <span class="list-value">{{ campaign.tweet_count }}</span>
                            </div>
                            <div class="action-count">
                                <span class="title">Actions</span>
                                <span class="list-value-total-actions">{{ campaign.action_count }}</span>
                            </div>
                        </td>
                        <td colspan="4"></td>
                    </tr>
                {% endfor %}
            </table>
        </div>

    {% else %}
        <div>You have no campaigns</div>
    {% endif %}
    <button class="create-campaign-button" style="margin-left:200px; margin-top:100px; margin-bottom:100px; height:55; background-color:green;"><a href="{% url 'campaign:create' %}" style="color:black;">Create Campaign</a></button>
    </div>
{% endblock %}

{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="{% static 'js/twitter-text-1.14.7.min.js' %}"></script>
<script src="{% static 'js/content_landing.js' %}"></script>
<script src="{% static 'js/content_landing_success_messages.js' %}"></script>
<script src="{% static 'js/content_landing_email_action.js' %}"></script>
<script src="{% static 'js/content_landing_tweet_action.js' %}"></script>
<script src="{% static 'js/content_landing_get_congress.js' %}"></script>

{% csrf_token %}
{% endblock %}